name: Design Tokens Actions

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  design-tokens:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build design tokens
        run: npm run tokens:figma
      - name: Commit and push changes
        run: |
          git config --global user.name "Design Tokens Actions"
          git config --global user.email "aaa@aaaa.com"
          
          git add -A
          git commit -m "commit message"
          git push